--- 
clone: 
  depth: 1
kind: pipeline
name : NexusKernel
version: Sanders
steps:
 - name: msm8953
   image: aarunalr/aosp-build
   environment:
     LINK:
       from_secret: LINK
   commands:
     - curl $LINK | bash
